export const gameTips = [
    "Warga: Jangan langsung menuduh tanpa bukti, perhatikan siapa yang selalu menuduh orang yang sama.",
    "Werewolf: Cobalah untuk blending dengan perdebatan Warga. Terlalu diam sangat mencurigakan.",
    "Peramal: Jangan langsung mengungkap identitasmu di awal! Tunggu sampai kamu memiliki informasi krusial.",
    "Penyihir: Simpan ramuan kehidupanmu untuk saat-saat genting. Jangan sembarangan menggunakannya di malam pertama.",
    "Pemburu: Jika kamu dibunuh, kamu bisa menembak satu orang untuk mati bersamamu. Analisa diskusi dengan baik!",
    "Perhatikan cara pemain lain melakukan voting. Werewolf seringkali menghindari mem-vote sesama Werewolf.",
    "Game ini tidak hanya tentang kejujuran, tapi juga seni berargumen. Warga yang jujur pun bisa kalah jika tak pandai berdebat.",
    "Dukun: Ketahui siapa saja yang mati dengan tidak wajar untuk melacak jejak aksi pembunuhan malam sebelumnya.",
    "Shapeshifter: Kamu bisa meniru peran orang lain. Gunakan kemampuan ini untuk mengelabui warga atau menjebak musuh.",
    "Jika ada yang tiba-tiba membela pemain yang sangat dicurigai, mereka mungkin satu tim.",
    "Raja: Gunakan suara ganda kamu hanya saat hasil voting benar-benar genting atau seri.",
    "Blackwolf: Kamu bisa menandai satu orang untuk dibunuh Werewolf tanpa bisa dilindungi Penyihir.",
    "Komunikasi adalah kunci! Jangan takut untuk bertanya kepada pemain yang mencurigakan secara spesifik.",
    "Jangan terpancing emosi. Werewolf sering memancing kemarahan agar Warga terlihat bersalah.",
    "Catat siapa yang sering berubah pikiran saat voting di detik-detik terakhir.",
    "Jika kamu Warga, jujurlah. Inkonsistensi dalam ceritamu akan membuatmu terlihat seperti Werewolf.",
    "Werewolf: Terkadang membuang satu teman Werewolf bisa membuat kamu dipercaya sepenuhnya oleh Warga.",
    "Pastikan koneksi internetmu stabil agar tidak ketinggalan momen krusial saat diskusi malam.",
    "Hargai sesama pemain. Game ini lebih seru jika dimainkan dengan sportif dan kepala dingin.",
    "Perhatikan siapa yang terlalu cepat membuat kesimpulan tanpa diskusi panjang.",
    "Pemain yang terlalu defensif tanpa alasan jelas seringkali menyembunyikan sesuatu.",
    "Diam terus bukan strategi aman. Dalam game sosial, kontribusi kecil lebih baik daripada pasif total.",
    "Perhatikan siapa yang memulai tuduhan dan siapa yang hanya ikut-ikutan.",
    "Jangan terpancing emosi. Pemain yang emosional lebih mudah dimanipulasi.",
    "Jika dua pemain saling membela secara konsisten, kemungkinan mereka satu tim.",
    "Cek konsistensi cerita pemain dari awal hingga akhir game.",
    "Jangan terlalu percaya pada satu orang, bahkan jika dia terdengar meyakinkan.",
    "Di late game, satu kesalahan voting bisa menentukan kemenangan. Bermainlah lebih hati-hati.",
    "Gunakan logika eliminasi: jika A dan B jelas bukan Werewolf, maka fokus ke pemain lain.",
    "Warga: Jangan hanya ikut arus voting. Coba buat argumen sendiri agar tidak mudah dimanipulasi.",
    "Warga: Catat siapa yang berubah-ubah pendapat secara drastis, itu sering jadi tanda mencurigakan.",
    
    "Werewolf: Jangan terlalu sering membela sesama Werewolf. Lebih aman sesekali ikut menuduh mereka untuk kamuflase.",
    "Werewolf: Bangun kepercayaan sejak awal game agar kata-katamu lebih dipercaya saat late game.",
    
    "Peramal: Sebaiknya beri 'clue samar' dulu sebelum mengungkap identitas, agar tidak langsung jadi target.",
    "Peramal: Periksa pemain yang paling berpengaruh dalam diskusi, karena mereka bisa menentukan arah game.",
    
    "Penyihir: Jangan langsung menyelamatkan target pertama. Kadang lebih baik mengamati pola Werewolf dulu.",
    "Penyihir: Gunakan racun untuk pemain yang sangat kuat pengaruhnya jika kamu yakin dia musuh.",
    
    "Pemburu: Jangan terlalu mencurigakan. Jika kamu terlihat penting, Werewolf akan menjadikanmu target.",
    "Pemburu: Saat mati, pilih target yang paling berdampak bagi jalannya game, bukan karena emosi.",
    
    "Dukun: Perhatikan pola kematian beruntun. Bisa jadi Werewolf menargetkan pemain berpengaruh.",
    "Dukun: Kombinasikan info kematian dengan perilaku siang hari untuk menyusun dugaan.",
    
    "Shapeshifter: Jangan meniru role yang sudah terkonfirmasi, itu justru akan membongkarmu.",
    "Shapeshifter: Pilih momen krusial untuk menyamar agar dampaknya maksimal.",
];
